service: rocketfy-challenge-backend
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    DATABASE_URL: {ssm:/rocketfy-challenge-backend/DATABASE_URL}

functions:
  productServices:
    timeout: 30
    handler: src/functions/product-services/index.handler
    events:
      - http:
          path: /products
          method: get
          cors: true
      - http:
          path: /products
          method: post
          cors: true
      - http:
          path: /products/{proxy+}
          method: any
          cors: true


package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node18
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10